# Generated by Django 5.0.1 on 2024-01-14 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default=uuid.uuid1, max_length=254, unique=True),
        ),
    ]
