# Generated by Django 5.0.1 on 2024-01-14 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSendingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_sent', models.IntegerField(default=0)),
                ('total_emails', models.IntegerField()),
                ('status', models.CharField(default='Not Started', max_length=20)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.emailtemplate')),
            ],
        ),
    ]
